# Generated by Django 2.1.1 on 2020-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('xCenter', models.CharField(max_length=100)),
                ('yCenter', models.CharField(max_length=100)),
                ('zCenter', models.CharField(max_length=100)),
            ],
        ),
    ]
