# Generated by Django 2.1.1 on 2020-03-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_auto_20200307_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
