# Generated by Django 2.1.1 on 2020-03-07 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20200307_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
