# Generated by Django 2.1.1 on 2020-03-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_auto_20200307_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='xCenter',
        ),
        migrations.RemoveField(
            model_name='box',
            name='yCenter',
        ),
        migrations.RemoveField(
            model_name='box',
            name='zCenter',
        ),
    ]
