# Generated by Django 2.1.1 on 2020-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_auto_20200308_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
