# Generated by Django 2.1.1 on 2021-04-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20210429_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='stateProvince',
            new_name='stateProvinceCode',
        ),
    ]
