# Generated by Django 2.2 on 2022-11-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
