# Generated by Django 2.1.1 on 2020-06-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_datetimeformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disableFillContainerAnimation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='disablePreviousNextItemAnimation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='multiBinPack',
            field=models.BooleanField(default=False),
        ),
    ]
