# Generated by Django 2.1.1 on 2020-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200623_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animationSpeed',
            field=models.IntegerField(default=50),
        ),
    ]
