# Generated by Django 2.1.1 on 2020-07-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_animationspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptionType',
            field=models.CharField(default='standard', max_length=12),
        ),
    ]
