# Generated by Django 2.1.1 on 2020-08-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_subscriptiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptionType',
        ),
    ]
