# Generated by Django 2.1.1 on 2020-11-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_subscriptiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usersTermsOfServiceRevision',
            field=models.IntegerField(default=0),
        ),
    ]
