# Generated by Django 2.1.1 on 2021-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='includeUpsContainers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='includeUspsContainers',
            field=models.BooleanField(default=False),
        ),
    ]
