# Generated by Django 2.1.1 on 2021-07-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210508_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shippoAccessToken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
