# Generated by Django 2.1.1 on 2020-06-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arrangements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('xDim', models.FloatField(default=0.0)),
                ('yDim', models.FloatField(default=0.0)),
                ('zDim', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('units', models.CharField(default='in', max_length=2)),
                ('cost', models.FloatField(default=0.0)),
                ('arrangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='arrangements.Arrangement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
