# Generated by Django 2.1.1 on 2020-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='container',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
