# Generated by Django 2.1.1 on 2021-04-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_container_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='shipment',
        ),
    ]
