# Generated by Django 2.1.1 on 2021-04-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20210320_1308'),
        ('containers', '0003_remove_container_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='shipments.Shipment'),
        ),
    ]
