# Generated by Django 2.1.1 on 2020-05-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0007_auto_20200523_1536'),
        ('containers', '0003_auto_20200516_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='arrangement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='arrangements.Arrangement'),
            preserve_default=False,
        ),
    ]
