# Generated by Django 2.1.1 on 2020-05-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_container_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='arrangements.Arrangement'),
        ),
    ]
