# Generated by Django 2.1.1 on 2020-05-24 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20200523_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='arrangements.Arrangement'),
        ),
        migrations.AlterField(
            model_name='container',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL),
        ),
    ]
