# Generated by Django 3.2.7 on 2022-03-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_remove_container_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
