# Generated by Django 2.2 on 2022-11-13 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0027_auto_20220806_0320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('containers', '0007_thirdpartycontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysedContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('xDim', models.FloatField(default=0.0)),
                ('yDim', models.FloatField(default=0.0)),
                ('zDim', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('units', models.CharField(default='in', max_length=2)),
                ('cost', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysedcontainers', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysedcontainers', to='shipments.Shipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
