# Generated by Django 2.2 on 2022-11-13 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0008_analysedcontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedcontainer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysedContainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysedcontainer',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysedContainers', to='shipments.Shipment'),
        ),
    ]
