# Generated by Django 2.1.1 on 2021-07-18 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_shipporateid'),
        ('shipposervice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippotransaction',
            name='quote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shippo_transactions', to='quotes.Quote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippotransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippo_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
