# Generated by Django 2.1.1 on 2021-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0002_auto_20210718_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippotransaction',
            name='label_url',
            field=models.CharField(blank=True, default='', max_length=1012, null=True),
        ),
    ]
