# Generated by Django 2.1.1 on 2021-07-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0003_auto_20210718_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippotransaction',
            name='objectCreated',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='objectId',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='objectOwner',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='objectState',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='objectUpdated',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='rateId',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='status',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='wasTest',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
