# Generated by Django 2.1.1 on 2021-07-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0004_auto_20210718_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippotransaction',
            old_name='wasTest',
            new_name='test',
        ),
    ]
