# Generated by Django 2.1.1 on 2021-07-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0005_auto_20210718_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippotransaction',
            old_name='rateId',
            new_name='shippoRateId',
        ),
    ]
