# Generated by Django 2.1.1 on 2021-07-20 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0007_auto_20210719_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippotransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippoTransaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippotransaction',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippoTransaction', to='quotes.Quote'),
        ),
    ]
