# Generated by Django 2.1.1 on 2021-08-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0008_auto_20210720_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('shippoTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippoMessage', to='shipposervice.ShippoTransaction')),
            ],
        ),
    ]
