# Generated by Django 2.1.1 on 2021-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0014_shipporefund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipporefund',
            name='objectState',
        ),
    ]
