# Generated by Django 2.1.1 on 2021-08-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0015_remove_shipporefund_objectstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipporefund',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippoRefund', to='shipposervice.ShippoTransaction'),
        ),
    ]
