# Generated by Django 3.2.7 on 2022-03-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipposervice', '0016_auto_20210815_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippomessage',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shipporefund',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shippotransaction',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
