# Generated by Django 2.1.1 on 2020-08-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20200819_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='owner',
        ),
    ]
