# Generated by Django 2.1.1 on 2020-08-19 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0005_remove_subscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
