# Generated by Django 2.1.1 on 2020-08-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripeId',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
