# Generated by Django 2.1.1 on 2020-09-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20200831_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripeId',
            new_name='stripeCustomerId',
        ),
    ]
