# Generated by Django 2.1.1 on 2020-09-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20200901_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripeSubscriptionId', models.CharField(default='null', max_length=50)),
                ('stripeSubscriptionItemDataPriceId', models.CharField(max_length=50)),
                ('stripeSubscriptionCurrentPeriodEnd', models.CharField(max_length=50)),
                ('stripeSubscriptionCustomer', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceid',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripeSubscriptionCurrentPeriodEnd',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripeSubscriptionCustomer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripeSubscriptionId',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripeSubscriptionItemDataPriceId',
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription'),
        ),
        migrations.AddField(
            model_name='invoiceid',
            name='stripeSubscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription.StripeSubscription'),
            preserve_default=False,
        ),
    ]
