# Generated by Django 2.1.1 on 2020-09-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_auto_20200910_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='current_period_end',
            new_name='currentPeriodEnd',
        ),
    ]
