# Generated by Django 2.1.1 on 2020-10-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0019_auto_20200911_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='itemsUsed',
        ),
    ]
