# Generated by Django 2.1.1 on 2020-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_remove_subscription_itemsused'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='itemsUsed',
            field=models.IntegerField(default=0),
        ),
    ]
