# Generated by Django 2.1.1 on 2020-10-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_subscription_itemsused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='itemsAllowed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='itemsUsed',
        ),
    ]
