# Generated by Django 2.1.1 on 2020-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_auto_20201003_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='itemsAllowed',
            field=models.IntegerField(default=0),
        ),
    ]
