# Generated by Django 2.1.1 on 2021-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0025_auto_20201214_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriptionUpdateInProgress',
            field=models.BooleanField(default=False),
        ),
    ]
