# Generated by Django 2.1.1 on 2021-02-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0026_subscription_subscriptionupdateinprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='containersAllowed',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='itemsAllowed',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shipmentsAllowed',
            field=models.IntegerField(default=50),
        ),
    ]
