# Generated by Django 2.1.1 on 2020-04-26 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('containers', models.CharField(blank=True, default='', max_length=100)),
                ('items', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ContainerLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('timedOut', models.BooleanField(default=False)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containerLayout', to='arrangements.Arrangement')),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('xCenter', models.FloatField(default=0.0)),
                ('yCenter', models.FloatField(default=0.0)),
                ('zCenter', models.FloatField(default=0.0)),
                ('containerLayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemList', to='arrangements.ContainerLayout')),
            ],
        ),
    ]
