# Generated by Django 2.1.1 on 2020-03-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bins', models.CharField(blank=True, default='', max_length=100)),
                ('boxes', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='BinLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('timedOut', models.BooleanField(default=False)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binLayout', to='arrangements.Arrangement')),
            ],
        ),
        migrations.CreateModel(
            name='BoxList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default='', max_length=100)),
                ('width', models.CharField(default='', max_length=100)),
                ('length', models.CharField(default='', max_length=100)),
                ('volume', models.CharField(default='', max_length=100)),
                ('xCenter', models.CharField(default='', max_length=100)),
                ('yCenter', models.CharField(default='', max_length=100)),
                ('zCenter', models.CharField(default='', max_length=100)),
                ('binLayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxList', to='arrangements.BinLayout')),
            ],
        ),
    ]
