# Generated by Django 2.1.1 on 2020-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='containers',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='items',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
