# Generated by Django 2.1.1 on 2021-02-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='title',
            field=models.CharField(default='My shipment', max_length=255),
        ),
    ]
