# Generated by Django 2.1.1 on 2020-05-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0002_auto_20200516_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='containers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrangements', to='containers.Container'),
        ),
    ]
