# Generated by Django 2.1.1 on 2020-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0002_arrangement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlist',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='xCenter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='yCenter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='zCenter',
            field=models.FloatField(default=0.0),
        ),
    ]
