# Generated by Django 2.1.1 on 2021-04-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0003_arrangement_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='shipments.Shipment'),
        ),
    ]
