# Generated by Django 2.1.1 on 2020-05-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0003_auto_20200522_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='containers',
        ),
    ]
