# Generated by Django 2.1.1 on 2020-05-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0006_auto_20200523_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='items',
        ),
    ]
