# Generated by Django 2.1.1 on 2020-05-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0008_auto_20200523_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='items',
        ),
    ]
