# Generated by Django 2.1.1 on 2020-05-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20200523_2238'),
        ('arrangements', '0009_auto_20200523_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='containers',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='containers.Container'),
        ),
    ]
