# Generated by Django 2.1.1 on 2020-05-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0012_auto_20200524_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='containers',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='containers.Container'),
        ),
    ]
