# Generated by Django 2.1.1 on 2020-05-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0013_auto_20200524_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='containers',
        ),
    ]
