# Generated by Django 2.1.1 on 2020-05-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0014_remove_arrangement_containers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerlayout',
            name='arrangement',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='containerLayout',
        ),
        migrations.DeleteModel(
            name='ContainerLayout',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
    ]
