# Generated by Django 2.1.1 on 2020-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0015_auto_20200525_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='multiBinPack',
            field=models.BooleanField(default=False),
        ),
    ]
