# Generated by Django 2.1.1 on 2021-03-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210319_2329'),
        ('shipments', '0002_auto_20210318_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipFromAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='addresses.Address'),
        ),
    ]
