# Generated by Django 2.1.1 on 2021-03-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210319_2329'),
        ('shipments', '0003_shipment_shipfromaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipToAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipToAddress', to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipFromAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipFromAddress', to='addresses.Address'),
        ),
    ]
