# Generated by Django 2.1.1 on 2021-03-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20210320_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipFromAddress',
            new_name='shipFromAddress8',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='shipToAddress',
            new_name='shipToAddress8',
        ),
    ]
