# Generated by Django 2.1.1 on 2021-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20210320_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipFromAddress8',
            new_name='shipFromAddress',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='shipToAddress8',
            new_name='shipToAddress',
        ),
    ]
