# Generated by Django 2.1.1 on 2021-03-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_auto_20210320_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipFromAddress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipmentIsFromAddress', to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipToAddress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipmentIsToAddress', to='addresses.Address'),
        ),
    ]
