# Generated by Django 2.1.1 on 2021-08-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20210320_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='timingInformation',
            field=models.CharField(default='No timeout info', max_length=255),
        ),
    ]
