# Generated by Django 2.2 on 2022-05-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_shipment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='validAddress',
            field=models.BooleanField(default=True),
        ),
    ]
