# Generated by Django 2.2 on 2022-05-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_shipment_validaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='validAddress',
        ),
        migrations.AddField(
            model_name='shipment',
            name='validFromAddress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='validToAddress',
            field=models.BooleanField(default=True),
        ),
    ]
