# Generated by Django 2.2 on 2022-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_auto_20220525_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='arrangementPossible',
        ),
        migrations.AddField(
            model_name='shipment',
            name='fitAllArrangementPossibleAPriori',
            field=models.BooleanField(default=False),
        ),
    ]
