# Generated by Django 2.2 on 2022-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_auto_20220529_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrangementFittingAllItemsFound',
            field=models.BooleanField(default=False),
        ),
    ]
