# Generated by Django 2.2 on 2022-07-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_shipment_arrangementfittingallitemsfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='usedAllContainers',
            field=models.BooleanField(default=True),
        ),
    ]
