# Generated by Django 2.2 on 2022-07-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_shipment_usedallcontainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='noValidRequests',
            field=models.BooleanField(default=False),
        ),
    ]
