# Generated by Django 2.2 on 2022-07-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_shipment_novalidrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='usedAllContainers',
            new_name='usedAllValidContainers',
        ),
    ]
