# Generated by Django 2.2 on 2022-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_auto_20220705_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='noErrorsMakingRequests',
            field=models.BooleanField(default=True),
        ),
    ]
