# Generated by Django 3.2.7 on 2022-08-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0018_shipment_noerrorsmakingrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='calculationInProgress',
            field=models.BooleanField(default=False),
        ),
    ]
