# Generated by Django 3.2.7 on 2022-08-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_shipment_calculationinprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='dummyField',
            field=models.BooleanField(default=False),
        ),
    ]
