# Generated by Django 3.2.7 on 2022-08-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0022_shipment_dummyfield3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='dummyField3',
        ),
        migrations.AddField(
            model_name='shipment',
            name='dummyField',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
