# Generated by Django 3.2.7 on 2022-08-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_auto_20220804_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='dummyField',
        ),
    ]
