# Generated by Django 2.2 on 2022-08-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_remove_shipment_dummyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='activeThreads',
            field=models.IntegerField(default=-1),
        ),
    ]
