# Generated by Django 2.2 on 2022-08-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0025_shipment_activethreads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='activeThreads',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
