# Generated by Django 2.2 on 2022-08-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0026_auto_20220806_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='activeThreads',
            field=models.IntegerField(default=-1),
        ),
    ]
