# Generated by Django 2.1.1 on 2020-06-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
