# Generated by Django 2.1.1 on 2021-01-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200625_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dummyField',
            field=models.CharField(default='here!!', max_length=255),
        ),
    ]
