# Generated by Django 2.1.1 on 2021-01-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_dummyfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dummyField',
        ),
    ]
