# Generated by Django 2.1.1 on 2020-05-23 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20200516_1329'),
        ('items', '0003_auto_20200516_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='containers.Container'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='xCenter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='yCenter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='zCenter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
