# Generated by Django 2.1.1 on 2020-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200523_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='xCenter',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='yCenter',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='zCenter',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
