# Generated by Django 2.1.1 on 2021-01-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_dummyfield2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dummyField2',
        ),
    ]
