# Generated by Django 2.1.1 on 2020-05-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangements', '0014_remove_arrangement_containers'),
        ('items', '0006_auto_20200524_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arrangements.Arrangement'),
        ),
    ]
