# Generated by Django 2.1.1 on 2021-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_dummyfield2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='weightUnits',
            field=models.CharField(default='lb', max_length=2),
        ),
    ]
