# Generated by Django 2.1.1 on 2021-03-18 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20210318_0029'),
        ('items', '0007_auto_20210314_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.Shipment'),
        ),
    ]
