# Generated by Django 3.2.7 on 2022-03-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210718_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
