# Generated by Django 2.1.1 on 2020-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('timedOut', models.BooleanField(default=False)),
            ],
        ),
    ]
