# Generated by Django 2.1.1 on 2021-03-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='carrier',
            field=models.CharField(default='My carrier', max_length=255),
        ),
    ]
