# Generated by Django 2.1.1 on 2021-03-19 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20210318_0029'),
        ('quotes', '0003_auto_20210318_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='shipments.Shipment'),
        ),
    ]
