# Generated by Django 2.1.1 on 2021-04-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20210430_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='scheduledDeliveryTime',
            field=models.CharField(blank=True, default='SCHEDULED DELIVERY TIME', max_length=255, null=True),
        ),
    ]
