# Generated by Django 2.1.1 on 2021-04-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20210430_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='daysToShip',
            field=models.CharField(blank=True, default='DAYS TO SHIP', max_length=255, null=True),
        ),
    ]
