# Generated by Django 2.1.1 on 2021-07-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20210430_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='shippoRateId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
