# Generated by Django 2.1.1 on 2021-08-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_shipporateid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('terms', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceLevel', to='quotes.Quote')),
            ],
        ),
    ]
